title: 林老师
description: 这是Pekko老师的个人 GitHub 页面
url: "https://pekkolin.github.io"

# 主题设置
theme: jekyll-theme-minimal

# 作者信息
author:
  name: pekkolin
  email: email@example.com

# 导航链接
nav:
  - {title: 首页, url: "/"}
  - {title: 学生座位表, url: "/学生座位表.html"}
  - {title: 倒数计时器, url: "/倒数计时器.html"}

# GitHub 设置
github:
  is_project_page: false

# 其他设置
markdown: kramdown
highlighter: rouge
