name: Pekko Lin
description: "Pekko Lin's Homepage"
baseurl: /pekkolin
url: http://pekkolin.github.io

social:
  github: pekkolin
  email: aydineray@mail.com
  facebook:
  twitter: erayaydi
  instagram:
  tumblr:
author:
  name: Pekko Lin
  bio: "Chinese 1, 2, 3, 4 & AP Chinese Teacher"
  email: aydineray@mail.com
  image: /assets/images/author.jpg
  github: erayaydin
  facebook: erayaydi
  twitter: erayaydi
  instagram:
  tumblr:
  show_on_post: true
permalink: /:categories/:title/
sass:
  style: compressed
paginate: 5
paginate_path: "/:num/"
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-gist

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
  - vendor
